spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.103.136:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Liufan!123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    root: info
    com.liufan.blog: info
  file: log/blog-pro.log 
server:
   port: 9080   