spring:
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  profiles:
    active: dev
  messages:
    basename: i18n/messages
    
comment.avatar: /images/avatar.png
  